#!/usr/bin/env python

# Copyright Anne Archibald 2011
# this code is under the LGPL

import sys
import time
from optparse import OptionParser

import paramiko

def wait_for_agent(keyname):
    """Wait until a particular private key is available from the SSH agent."""

    A = ()
    while not A:
        A = paramiko.Agent()
        time.sleep(1)
    
    keys_base64 = set()
    while True:
        for k in A.get_keys():
            b = k.get_base64()
            if b.startswith(keyname):
                return
        time.sleep(1)

if __name__=='__main__':
    prog, keyname = sys.argv
    wait_for_agent(keyname)
    
